import type { Metadata } from 'next';
import { DM_Mono, Space_Grotesk } from 'next/font/google';
import { Toaster } from "@/components/ui/sonner"
import { Providers } from "./providers"
import './globals.css';

const geistSans = Space_Grotesk({
  variable: '--font-app-sans',
  subsets: ['latin'],
});

const geistMono = DM_Mono({
  subsets: ['latin'],
  variable: '--font-app-mono',
  weight: '400',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'BRS',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
